### ISSUE TITLE
Supabase OAuth integration with Plasmo

### ISSUE THREAD

**Issue by jjcantu** [remusris/plasmo_tailwinds_supabase_scaffold#1]
Hi @remusris! 
Do you have any tips on integrating Supabase's GitHub OAuth with Plasmo? I've been working on this for a while. I set up an event listener in one of my service workers to store the session after user sign-in, but the event never seems to trigger, and I’m not entirely sure why. 

Any guidance or advice would be greatly appreciated—thank you!

**Comment by remusris** [comment]
> Hi @remusris! 
> 
> Do you have any tips on integrating Supabase's GitHub OAuth with Plasmo? I've been working on this for a while. I set up an event listener in one of my service workers to store the session after user sign-in, but the event never seems to trigger, and I’m not entirely sure why. 
> 
> 
> 
> Any guidance or advice would be greatly appreciated—thank you!

I haven't done this yet but I think you'll find this link useful for supabase oauth in a chrome extension.

https://gourav.io/blog/supabase-auth-chrome-extension

**Comment by jjcantu** [comment]
Dang, I've been looking for resources everywhere and was not able to find any. Thanks!
